CREATE DATABASE DAREDE
GO 

USE DAREDE
GO




CREATE TABLE USUARIO (
  idUsuario INT PRIMARY KEY IDENTITY,
  email VARCHAR(256) UNIQUE NOT NULL,
  senha VARCHAR(20) NOT NULL,
  statusUsuario VARCHAR(15) NOT NULL
);
GO


CREATE TABLE ADMINISTRADOR (
  idAdministrador TINYINT PRIMARY KEY IDENTITY,
  idUsuario INT FOREIGN KEY REFERENCES USUARIO(idUsuario),
  imgADM VARCHAR(256) NOT NULL,
  cnpjADM VARCHAR(18) NOT NULL,
  enderecoADM VARCHAR(256) NOT NULL,
  estadoADM VARCHAR(25) NOT NULL,
  cidadeADM VARCHAR(30) NOT NULL,
  numeroTelADM VARCHAR(15) NOT NULL,
);
GO


CREATE TABLE FUNCIONARIO (
  idFuncionario TINYINT PRIMARY KEY IDENTITY,
  idUsuario INT FOREIGN KEY REFERENCES USUARIO(idUsuario),
  imgF VARCHAR(256) NOT NULL,
  nomeF VARCHAR(50) NOT NULL,
  cpfF VARCHAR(14) NOT NULL,
  rgF VARCHAR(12) NOT NULL,
  dataNascimentoF VARCHAR(10) NOT NULL,
  enderecoF VARCHAR(256) NOT NULL,
  estadoF VARCHAR(25) NOT NULL,
  cidadeF VARCHAR(30) NOT NULL,
  numeroTelF VARCHAR(15) ,
  numeroCelF VARCHAR(15) NOT NULL,
  situacaoFuncionario VARCHAR(15) NOT NULL
);
GO


CREATE TABLE EMPRESA (
  idEmpresa INT PRIMARY KEY IDENTITY,
  idFuncionario TINYINT FOREIGN KEY REFERENCES FUNCIONARIO(idFuncionario),
  idUsuario INT FOREIGN KEY REFERENCES USUARIO(idUsuario),
  imgE VARCHAR(256) NOT NULL,
  nomeE VARCHAR(50) NOT NULL,
  cnpjE VARCHAR(18) NOT NULL,
  enderecoE VARCHAR(256) NOT NULL,
  estadoE VARCHAR(25) NOT NULL,
  cidadeE VARCHAR(30) NOT NULL,
  numeroTelE VARCHAR(15) ,
  numeroCelE VARCHAR(15) NOT NULL,
);
GO






CREATE TABLE SITUACAO_EQUIPAMENTO (
  idSituacaoEquipamento TINYINT PRIMARY KEY IDENTITY,
  situacaoEquipamento VARCHAR(30) NOT NULL,
);
GO


CREATE TABLE EQUIPAMENTO (
  idEquipamento TINYINT PRIMARY KEY IDENTITY,
  idEmpresa INT FOREIGN KEY REFERENCES USUARIO(idUsuario),
  idSituacaoEquipamento TINYINT FOREIGN KEY REFERENCES SITUACAO_EQUIPAMENTO(idSituacaoEquipamento),
  nomeEquipamento VARCHAR(30) NOT NULL,
);
GO



CREATE TABLE VPC (
  idVPC INT PRIMARY KEY IDENTITY,
  idEquipamento TINYINT FOREIGN KEY REFERENCES EQUIPAMENTO(idEquipamento),
  tagNome VARCHAR(256) NOT NULL,
  blocoCIDR VARCHAR(256) NOT NULL,
  zonaDisponibilidade VARCHAR(10) NOT NULL,
  subRedesPublica VARCHAR(256) NOT NULL,
  blocoCIDRpublica VARCHAR(256) NOT NULL,
  nsubRedesPrivada VARCHAR(256) NOT NULL,
  blocoCIDprivada VARCHAR(256) NOT NULL,
  gateway VARCHAR(256) NOT NULL,
  endpointVPC VARCHAR(256) NOT NULL,
);
GO

CREATE TABLE EC2 (
  idEC2 INT PRIMARY KEY IDENTITY,
  idVPC INT FOREIGN KEY REFERENCES VPC(idVPC),
  SO VARCHAR(256) NOT NULL,
  tipoInstancia VARCHAR(256) NOT NULL,
  quantidadeInstancia VARCHAR(256) NOT NULL,
  rede VARCHAR(256) NOT NULL,
  subRede VARCHAR(256) NOT NULL,
  ipPublico VARCHAR(256) NOT NULL,
  armazenamento VARCHAR(256) NOT NULL,
  chave VARCHAR(256) not null,
  valor VARCHAR(256) NOT NULL,
  numeroGSeguranca VARCHAR(256) NOT NULL,
  descricaoGrupo VARCHAR(256) NOT NULL,
  tipoRegra VARCHAR(256) NOT NULL,
  protocolo VARCHAR(256) NOT NULL,
  parChaves VARCHAR(256) NOT NULL,
  statusEC2 VARCHAR(256) NOT NULL,
);
GO


